---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nqatsxqe/primepolicies.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/rm $DEPLOYPATH/.cpanel.yml
    - /bin/rm $DEPLOYPATH/.gitignore
---
